### ISSUE TITLE
[Spell][Hunter] Detterence

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1000]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Detterence nie powinien zapewniać ochrony parry przed spellami graczy z "positionnal requirement". Jest to Backstab oraz Shred.

http://www.arenajunkies.com/topic/165708-druid-shread/
http://www.arenajunkies.com/topic/143458-shs-spec-rogues-backstab-ambush-penetrating-deterrence/
https://us.battle.net/forums/en/wow/topic/1253415820

"AND... not many hunters know this BUT any attack with a positional requirement GOES RIGHT THROUGH DETERRENCE. Shred and backstab don't give a damn about deterrence."

"All attacks that require you to be behind your target work through detterance for some reason, i think feral shred works too, probably just an oversight with parry mechanics :0 "

"It's a leftover mechanic from TBC. Backstab/shred/ambush (and mut back then) were getting dodge/parried/blocked on targets that were in the motion of turning around. So their fix was to make those abilities not avoidable since that is the case with attacks from behind anyways. "

"Yes detterence is supposed to make you parry everything... BUT you can't parry spell comin from stealth/positionnal requirement. It includes backstab, shred, and all stealth skills, cs, pounce etc."

Polecam przejrzeć dokładnie tematy, jasno z nich wynika jak powinno to działać.

**Obecne działanie**: Obecnie Detterence zapewnia ochronę przed Backstabem oraz Shredem, wynika to z błędnej interpretacji  "Patch 3.2.0 (04-Aug-2009): This ability now allows the hunter to parry spells and attacks from behind as well as in front. Now has a new visual spell effect."

**Oczekiwane działanie**: Żaden gracz nie powinien mieć opcji parrowania/dodgowania/blockowania spelli, które są wykonywane ze stealtha lub posiadają "positionnal requirement". Nawet po użyciu spella typu Detterence.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Warto również dodać, że według wowwiki działanie o którym piszesz zostało naprawione i ataki, których normalnie nie dało się parować były już blokowane na 4.0.6.

**Comment by Crackaw** [comment]
Sprawdzałem u siebie i działa prawidło. Jakby ktoś mógłby potwierdzić moje słowa to byłbym wdzięczny.

**Comment by Danieloses** [comment]
Sprawdziłem właśnie na feronisie i nadal backstab jest parrowany przez detterence, nie wiem jak z shredem.

**Comment by bugbuster20** [comment]
shred również.

**Comment by ghost** [comment]
Overpower warków może przejść przez dete tylko gdy maja glyph (do sprawdzenia):
Patch 3.2.0 "Warriors wont still be able to spam overpower since its 100% parry(and overpower is only avaliable with dodge/taste for blood) only if they have Glyph of Overpower(and alot of arms warrs probably will have it), this will be the total deterrence ownage."
Dete chroni przed falami na OS i przed Laser Barrage (u nas trzeba sprawdzić, jak bede miał chwile to to zrobię):
Patch 3.1.3 "Works against Flame Walls of Sartharion and laser barrage" 
Dete powinien dawać skill up w broniach mele, które ma założone hunter, aktualnie u nas tak nie działa:
Patch 3.0.8 "I don't know if it's been mentioned here, but deterrence actually levels up your weapon skill after 3.0.8."
Rogal jak i druid może bić nas przez dete każdym spellem ze stealth, ponieważ ataków ze stealth nie można uniknąć, ani sparować (u nas chyba działa poprawnie). W każdym razie, gdy rogue wyjdzie ze stealth nie może już nas bić, chyba, ze ma szadoł denca to se może :P (a to to już trzeba przetestować). 
Dete powinien nas chronić z każdej strony:
 "Patch 3.2.0 (04-Aug-2009): This ability now allows the hunter to parry spells and attacks from behind as well as in front. Now has a new visual spell effect."

źródła: 
http://www.wowhead.com/spell=19263/deterrence#comments
http://wowwiki.wikia.com/wiki/Deterrence

Jak będę mieć trochę więcej czasu to wszystko co tu wypisałem sprawdzę.
