### ISSUE TITLE
Używanie potionów,a  generowany threat

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#130]
**Opis**: Kiedy napijemy się potionu, a np nasz pet tankuje zrywa często z niego agro na nas

**Obecne działanie**: Problem jest taki, że zrywa się agro po wypiciu potionu np na życie.

**Oczekiwane działanie**: Potiony nie powinny generować threat'u

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zejść z hp do małej ilości
2. np Void niech tankuje lu pet huntera
3. Napić się potionu na HP

**Comment by xsitdev** [comment]
Threat caused by beneficial effects is divided amongst all NPCs that are aware of the character. This global threat applies to heals, bonus threat from buffs (such as Battle Shout or Arcane Brilliance), and power gains (such as a Mana Potion or Rage Potion).

Healing threat is global, and is normally .5x of the amount healed. Healing effects cause no threat if the target is already at full health.

Potion moze generowac threat jak napisane wyzej, Twoj widocznie przebil threat voida.
